apiVersion: choreo.io/v1alpha1
kind: Component
metadata:
  name: exchange-services
  description: Exchange microservices for data sharing
spec:
  # Define multiple services in a single component
  services:
    - name: consent-engine
      type: web
      dockerfile: consent-engine/Dockerfile
      buildContext: .
      port: 8081
      env:
        - name: ENVIRONMENT
          value: production
        - name: PORT
          value: "8081"
    
    - name: policy-decision-point
      type: web
      dockerfile: policy-decision-point/Dockerfile
      buildContext: .
      port: 8082
      env:
        - name: ENVIRONMENT
          value: production
        - name: PORT
          value: "8082"
    
    - name: orchestration-engine-go
      type: web
      dockerfile: orchestration-engine-go/Dockerfile
      buildContext: .
      port: 8083
      env:
        - name: ENVIRONMENT
          value: production
        - name: PORT
          value: "8083"
