apiVersion: choreo.io/v1alpha1
kind: Component
metadata:
  name: exchange-services-monolithic
  description: Monolithic Exchange Services - Data sharing platform with policy enforcement and consent management
spec:
  # Single monolithic service configuration
  services:
    - name: exchange-platform
      type: web
      dockerfile: Dockerfile
      buildContext: .
      # Expose multiple ports for different services
      ports:
        - port: 4000
          name: orchestration-engine
          protocol: TCP
        - port: 8081
          name: consent-engine
          protocol: TCP
        - port: 8082
          name: policy-decision-point
          protocol: TCP
      env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: info
        - name: LOG_FORMAT
          value: json
        - name: BUILD_VERSION
          value: latest
        - name: BUILD_TIME
          value: ""
        - name: GIT_COMMIT
          value: ""

  # Multiple endpoints for different services
  endpoints:
    - name: orchestration-engine-api
      displayName: Orchestration Engine API
      service:
        basePath: /
        port: 4000
      type: GraphQL
      networkVisibilities: 
        - Public
        - Organization
    
    - name: consent-engine-api
      displayName: Consent Management Engine API
      service:
        basePath: /
        port: 8081
      type: REST
      networkVisibilities: 
        - Public
        - Organization
    
    - name: policy-decision-point-api
      displayName: Policy Decision Point API
      service:
        basePath: /
        port: 8082
      type: REST
      networkVisibilities: 
        - Public
        - Organization

  # Runtime configurations
  configurations:
    env:
      - name: ENVIRONMENT
        valueFrom:
          configForm:
            displayName: Environment
            required: true
            type: string
            defaultValue: production
      - name: LOG_LEVEL
        valueFrom:
          configForm:
            displayName: Log Level
            required: false
            type: string
            defaultValue: info
      - name: LOG_FORMAT
        valueFrom:
          configForm:
            displayName: Log Format
            required: false
            type: string
            defaultValue: json
