version: '3.8'

services:
  api-server:
    build: .
    ports:
      - "3000:80"
    environment:
      - PORT=3000
      - ASGARDEO_BASE_URL=${ASGARDEO_BASE_URL:-https://api.asgardeo.io/t/lankasoftwarefoundation}
      - ASGARDEO_CLIENT_ID=${ASGARDEO_CLIENT_ID}
      - ASGARDEO_CLIENT_SECRET=${ASGARDEO_CLIENT_SECRET}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3