package tests

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gov-dx-sandbox/api-server-go/handlers"
	"github.com/gov-dx-sandbox/api-server-go/models"
)

// TestConsumerHandlers tests consumer management endpoints
func TestConsumerHandlers(t *testing.T) {
	apiServer := handlers.NewAPIServer()
	mux := http.NewServeMux()
	apiServer.SetupRoutes(mux)

	t.Run("POST /consumers", func(t *testing.T) {
		reqBody := models.CreateConsumerRequest{
			ConsumerName: "Test Consumer",
			ContactEmail: "test@example.com",
			PhoneNumber:  "1234567890",
		}

		jsonBody, _ := json.Marshal(reqBody)
		req := httptest.NewRequest("POST", "/consumers", bytes.NewBuffer(jsonBody))
		req.Header.Set("Content-Type", "application/json")

		w := httptest.NewRecorder()
		mux.ServeHTTP(w, req)

		if w.Code != http.StatusCreated {
			t.Errorf("Expected status 201, got %d", w.Code)
		}

		var response map[string]interface{}
		json.Unmarshal(w.Body.Bytes(), &response)

		// Response should contain data directly
	})

	t.Run("GET /consumers", func(t *testing.T) {
		req := httptest.NewRequest("GET", "/consumers", nil)
		w := httptest.NewRecorder()
		mux.ServeHTTP(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("Expected status 200, got %d", w.Code)
		}
	})

	t.Run("POST /consumer-applications/{consumerId}", func(t *testing.T) {
		// Create consumer first
		consumer := createTestConsumerViaAPI(t, mux)

		appReq := models.CreateConsumerAppRequest{
			ConsumerID:     consumer.ConsumerID,
			RequiredFields: map[string]bool{"person.fullName": true},
		}

		jsonBody, _ := json.Marshal(appReq)
		req := httptest.NewRequest("POST", "/consumer-applications/"+consumer.ConsumerID, bytes.NewBuffer(jsonBody))
		req.Header.Set("Content-Type", "application/json")

		w := httptest.NewRecorder()
		mux.ServeHTTP(w, req)

		if w.Code != http.StatusCreated {
			t.Errorf("Expected status 201, got %d", w.Code)
		}
	})
}

// Health endpoints are tested in main_test.go

// Helper functions for API testing
func createTestConsumerViaAPI(t *testing.T, mux *http.ServeMux) *models.Consumer {
	reqBody := models.CreateConsumerRequest{
		ConsumerName: "Test Consumer",
		ContactEmail: "test@example.com",
		PhoneNumber:  "1234567890",
	}

	jsonBody, _ := json.Marshal(reqBody)
	req := httptest.NewRequest("POST", "/consumers", bytes.NewBuffer(jsonBody))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Failed to create consumer: status %d", w.Code)
	}

	var consumerData map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &consumerData)

	return &models.Consumer{
		ConsumerID:   consumerData["consumerId"].(string),
		ConsumerName: consumerData["consumerName"].(string),
		ContactEmail: consumerData["contactEmail"].(string),
		PhoneNumber:  consumerData["phoneNumber"].(string),
	}
}

func createAndApproveTestAppViaAPI(t *testing.T, mux *http.ServeMux, consumerID string) *models.ConsumerApp {
	// Create application
	appReq := models.CreateConsumerAppRequest{
		ConsumerID:     consumerID,
		RequiredFields: map[string]bool{"person.fullName": true},
	}

	jsonBody, _ := json.Marshal(appReq)
	req := httptest.NewRequest("POST", "/consumer-applications/"+consumerID, bytes.NewBuffer(jsonBody))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Failed to create application: status %d", w.Code)
	}

	var appData map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &appData)

	submissionID := appData["submissionId"].(string)

	// Approve application
	updateReq := models.UpdateConsumerAppRequest{
		Status: &[]models.ApplicationStatus{models.StatusApproved}[0],
	}

	jsonBody, _ = json.Marshal(updateReq)
	req = httptest.NewRequest("PUT", "/consumer-applications/"+submissionID, bytes.NewBuffer(jsonBody))
	req.Header.Set("Content-Type", "application/json")

	w = httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("Failed to approve application: status %d", w.Code)
	}

	// Return the approved application - credentials will be generated by the service
	return &models.ConsumerApp{
		SubmissionID: submissionID,
		ConsumerID:   consumerID,
		Status:       models.StatusApproved,
		Credentials:  nil, // Will be generated by the service
	}
}
