services:
  opa_server:
    image: openpolicyagent/opa:latest
    container_name: opa_server
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies
      - ./data:/data
    command:
      - run
      - --server
      - --addr=0.0.0.0:8181 
      - --log-level=debug
      - --set=decision_logs.console=true
      - /policies
  pce_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pce_app
    ports:
      - "8080:8080"
    depends_on:
      opa_server:
        condition: service_started 
    environment:
      - OPA_URL=http://opa_server:8181/v1/data/opendif/authz/decision