apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-drp-deployment
  labels:
    app: mock-drp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-drp
  template:
    metadata:
      labels:
        app: mock-drp
    spec:
      containers:
        - name: ballerina-container
          image: gov-dx-sandbox/mock-drp:v0.1.0
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: mock-drp-service
spec:
  selector:
    app: mock-drp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090